/* ============================================
   TEXTOS EN LOS 4 IDIOMAS
   Aqui guardo todos los textos de la pagina.
   En el HTML cada elemento tiene data-texto="clave"
   y el archivo main.js se encarga de cambiarlos.
   ============================================ */

var textos = {

    /* ---------- ESPANOL ---------- */
    es: {
        nav_inicio: "Inicio",
        nav_restaurante: "Restaurante",
        nav_lodge: "Lodge Hotel",
        nav_travel: "Travel Explore",
        nav_contacto: "Contacto",
        nav_reservar: "Reservar",
        menu_abrir: "Menu",

        portada_sub: "Una experiencia en las alturas del Ecuador",
        portada_texto: "Gastronomia, hospedaje y aventura a los pies del Nevado Chimborazo.",
        portada_boton1: "Conocer mas",
        portada_boton2: "Reservar",

        destino_titulo: "Mucho mas que un destino",
        destino_p1: "Chimborazo Rey ofrece una experiencia turistica completa en uno de los paisajes mas impresionantes del Ecuador. En un mismo lugar puedes comer, descansar y conocer la montana.",
        destino_p2: "Trabajamos junto a la comunidad de Cruz del Arenal, en la via Guaranda - Ambato.",
        punto1: "Restaurante de aventura",
        punto2: "Lodge Hotel",
        punto3: "Turismo de aventura",
        punto4: "Cultura andina",
        punto5: "Naturaleza",
        punto6: "Gastronomia",
        punto7: "Hospitalidad",
        punto8: "Turismo comunitario",

        exp_titulo: "Nuestras tres areas",
        exp1_titulo: "Restaurante de Aventura",
        exp1_texto: "Comida nacional e internacional, opciones veganas, coffee shop y cerveza artesanal propia.",
        exp1_boton: "Ver restaurante",
        exp2_titulo: "Lodge Hotel",
        exp2_texto: "Habitaciones familiares, grupales y matrimoniales con calefaccion y vista al nevado.",
        exp2_boton: "Ver Lodge",
        exp3_titulo: "Travel Explore",
        exp3_texto: "Ascensos, cabalgatas, ciclismo y trekking nocturno con guias especializados.",
        exp3_boton: "Ver aventuras",

        nosotros_titulo: "Sobre nosotros",
        nosotros_p1: "Chimborazo Rey esta ubicado en un punto estrategico de la via Guaranda - Ambato, a los pies del Nevado Chimborazo.",
        nosotros_p2: "Queremos ser un referente turistico de Guaranda y de la provincia de Bolivar, promoviendo el turismo comunitario.",

        mision_titulo: "Mision",
        mision_texto: "Brindar una experiencia turistica completa y de calidad que una hospedaje, gastronomia y aventura, con hospitalidad familiar y compromiso con la comunidad de Cruz del Arenal.",
        mision1: "Hospedaje calido y seguro",
        mision2: "Gastronomia de altura",
        mision3: "Experiencias con guias",
        mision4: "Desarrollo sostenible",

        vision_titulo: "Vision 2030",
        vision_texto: "Ser un referente de turismo comunitario y sostenible de Bolivar y de la region andina del Ecuador, destacando por la calidad del servicio y su impacto positivo.",
        vision1: "Excelencia en el servicio",
        vision2: "Impacto economico local",
        vision3: "Valoracion cultural",
        vision4: "Cuidado del ambiente",

        valores_titulo: "Nuestros valores",
        valor1_titulo: "Sostenibilidad",
        valor1_texto: "Cuidamos el paramo que nos rodea y promovemos practicas responsables.",
        valor2_titulo: "Comunidad",
        valor2_texto: "Trabajamos con la comunidad de Cruz del Arenal para generar beneficios compartidos.",
        valor3_titulo: "Hospitalidad",
        valor3_texto: "Recibimos a cada visitante como parte de la familia.",
        valor4_titulo: "Excelencia",
        valor4_texto: "Mejoramos siempre nuestros servicios para dar experiencias seguras.",
        valor5_titulo: "Cultura",
        valor5_texto: "Valoramos y compartimos la cultura andina de este territorio.",

        ubicacion_titulo: "Donde estamos",
        ubicacion_texto: "Estamos en el sector Cruz del Arenal, en la via Guaranda - Ambato, a unos 4.250 metros sobre el nivel del mar.",
        ubi_pais: "Pais",
        ubi_provincia: "Provincia",
        ubi_canton: "Canton",
        ubi_sector: "Sector",
        ubi_via: "Via",
        ubi_altitud: "Altitud",
        ubi_altitud_dato: "4.250 m s. n. m. aprox.",
        ubi_nota: "Nota: aqui se debe colocar el mapa oficial de Google Maps del negocio.",

        contacto_titulo: "Contactanos",
        contacto_texto: "Escribenos para reservar una mesa, consultar hospedaje o planificar tu aventura.",
        contacto_info: "Informacion",
        contacto_tel: "Telefono",
        contacto_correo: "Correo",
        boton_llamar: "Llamar",
        boton_whatsapp: "WhatsApp",
        boton_correo: "Enviar correo",
        boton_mapa: "Como llegar",

        pie_nav: "Navegacion",
        pie_contacto: "Contacto",
        pie_ubicacion: "Ubicacion",
        pie_derechos: "Todos los derechos reservados.",
        wa_flotante: "Escribenos",

        form_nombre: "Nombre completo",
        form_telefono: "Telefono",
        form_correo: "Correo electronico",
        form_comentarios: "Comentarios",
        form_enviar: "Enviar solicitud",
        form_aviso: "Este formulario no guarda datos en ningun servidor. Al enviarlo se abre WhatsApp con el resumen.",

        resto_titulo: "Sabores en las alturas",
        resto_texto: "Una experiencia gastronomica a 4.250 metros sobre el nivel del mar.",
        resto_boton1: "Ver el menu",
        resto_boton2: "Reservar mesa",
        resto_sobre: "Sobre el restaurante",
        resto_p1: "Ofrecemos platos nacionales e internacionales, y tambien opciones veganas y vegetarianas.",
        resto_p2: "Tenemos coffee shop, cerveza artesanal Chimborazo Rey, amplios salones y un ambiente acogedor.",
        serv1_titulo: "Comida nacional e internacional",
        serv1_texto: "Platos ecuatorianos y tambien internacionales.",
        serv2_titulo: "Opciones veganas",
        serv2_texto: "Alternativas veganas y vegetarianas.",
        serv3_titulo: "Coffee shop",
        serv3_texto: "Cafe y bebidas calientes para el frio.",
        serv4_titulo: "Cerveza artesanal",
        serv4_texto: "Nuestra propia cerveza Chimborazo Rey.",
        serv5_titulo: "Amplios salones",
        serv5_texto: "Espacio para grupos y familias.",
        serv6_titulo: "Ambiente acogedor",
        serv6_texto: "Un lugar calido despues de la montana.",
        pagos_titulo: "Formas de pago",
        pago1: "Tarjeta",
        pago2: "Efectivo",
        pago3: "Transferencia",

        menu_titulo: "Nuestro menu",
        menu_texto: "Usa los botones para ver los platos por categoria.",
        filtro_todos: "Todos",
        cat_pollo: "Pollo",
        cat_cerdo: "Cerdo",
        cat_carnes: "Carnes",
        cat_pescados: "Pescados",
        cat_camarones: "Camarones",
        cat_tradicional: "Tradicionales",
        cat_desayunos: "Desayunos",
        cat_almuerzos: "Almuerzos",
        cat_cafeteria: "Cafeteria",
        plato_pendiente: "Plato por definir",
        plato_texto: "Espacio reservado para un plato de esta categoria.",
        precio_pendiente: "Precio por confirmar",
        menu_aviso: "Importante: los platos y precios se deben copiar del menu oficial de Chimborazo Rey.",

        galeria_titulo: "Galeria de fotos",
        galeria_texto: "Haz clic en una foto para verla mas grande.",

        reserva_titulo: "Reservar una mesa",
        form_personas: "Numero de personas",
        form_fecha: "Fecha",
        form_hora: "Hora",

        lodge_titulo: "Descansa entre las montanas",
        lodge_texto: "Hospedaje a unos 4.250 metros sobre el nivel del mar, a las faldas del Chimborazo.",
        lodge_boton: "Consultar disponibilidad",
        hab_titulo: "Nuestras habitaciones",
        hab1_titulo: "Habitaciones familiares",
        hab1_texto: "Espacios amplios para que la familia descanse junta.",
        hab2_titulo: "Habitaciones grupales",
        hab2_texto: "Ideales para grupos de viajeros y expediciones.",
        hab3_titulo: "Habitaciones matrimoniales",
        hab3_texto: "Un espacio comodo y calido para parejas.",
        hab_precio: "Precio bajo consulta.",
        hab_boton: "Consultar",

        servicios_titulo: "Servicios del hotel",
        sh1: "Calefaccion",
        sh2: "Seguridad 24 horas",
        sh3: "Camaras de seguridad",
        sh4: "Internet",
        sh5: "Television por cable",
        sh6: "Area de cocina",
        sh7: "Sala de estar",
        sh8: "Paquetes turisticos",
        sh9: "Vista al nevado",

        reserva_lodge: "Solicitar hospedaje",
        form_nacionalidad: "Nacionalidad",
        form_tipo: "Tipo de habitacion",
        form_huespedes: "Numero de huespedes",
        form_entrada: "Fecha de entrada",
        form_salida: "Fecha de salida",
        reco_titulo: "Recomendaciones",
        reco1: "Llega con tiempo y descansa antes de subir.",
        reco2: "Toma bastante agua durante el dia.",
        reco3: "Trae ropa abrigada, las noches son frias.",
        reco4: "Preguntanos por los paquetes turisticos.",

        travel_titulo: "La montana te espera",
        travel_texto: "Experiencias en el paramo andino con guias especializados y equipo de montana.",
        travel_boton: "Ver actividades",
        act_titulo: "Nuestras actividades",
        act1_titulo: "Cumbre Volcan Chimborazo",
        act1_texto: "Ascenso a la cumbre del volcan mas alto del Ecuador.",
        act2_titulo: "Cumbre Volcan Carihuairazo",
        act2_texto: "Ascenso a la cumbre central del Carihuairazo, vecino del Chimborazo.",
        act3_titulo: "Cabalgatas",
        act3_texto: "Rutas a caballo hacia aguas termales, miradores, las antenas, el Carihuairazo y la Laguna Congelada.",
        act4_titulo: "Descenso en bicicleta",
        act4_texto: "Bajada en bicicleta desde las alturas del Chimborazo.",
        act5_titulo: "Trekking nocturno",
        act5_texto: "Caminata de noche para ver las constelaciones y escuchar las historias de la zona.",
        act_dificultad: "Dificultad",
        act_precio: "Precio",
        act_ver: "Ver detalle",
        act_consultar: "Consultar",
        act_sin_precio: "Precio bajo consulta",
        act_incluye: "Que incluye",
        act_equipo: "Equipo",
        act_recomendaciones: "Recomendaciones",
        act_cerrar: "Cerrar",

        niveles_titulo: "Niveles de dificultad",
        nivel_bajo: "Bajo",
        nivel_bajo_medio: "Bajo - Medio",
        nivel_medio: "Medio",
        nivel_medio_alto: "Medio - Alto",
        nivel_bajo_txt: "Para casi todos los visitantes, sin experiencia previa.",
        nivel_bajo_medio_txt: "Necesita condicion fisica basica.",
        nivel_medio_txt: "Necesita buena condicion fisica y adaptacion a la altura.",
        nivel_medio_alto_txt: "Actividad exigente de alta montana.",
        niveles_nota: "Estos niveles son referenciales y se confirman al momento de reservar.",

        seguridad_titulo: "Seguridad",
        seguridad_texto: "Cada salida se planifica con guias, equipo de montana y acompanamiento.",
        seg1: "Guias especializados",
        seg2: "Guias certificados cuando corresponde",
        seg3: "Primeros auxilios",
        seg4: "Transporte en algunas actividades",
        seg5: "Equipo de montana",
        seg6: "Cascos",
        seg7: "Arnes",
        seg8: "Cuerdas",
        seg9: "Piolet",
        seg10: "Crampones",
        seg11: "Linterna frontal",
        seg12: "Bastones de trekking",
        seguridad_aviso: "Importante: ninguna actividad de montana esta libre de riesgos. La salida puede cambiar o cancelarse por el clima o por el estado del grupo. El guia siempre decide pensando en la seguridad.",

        consulta_titulo: "Consultar una actividad",
        form_actividad: "Actividad que te interesa",
        form_participantes: "Numero de participantes",
        form_elegir: "Elige una opcion"
    },

    /* ---------- INGLES ---------- */
    en: {
        nav_inicio: "Home",
        nav_restaurante: "Restaurant",
        nav_lodge: "Lodge Hotel",
        nav_travel: "Travel Explore",
        nav_contacto: "Contact",
        nav_reservar: "Book now",
        menu_abrir: "Menu",

        portada_sub: "An experience in the highlands of Ecuador",
        portada_texto: "Food, lodging and adventure at the foot of the Chimborazo volcano.",
        portada_boton1: "Learn more",
        portada_boton2: "Book now",

        destino_titulo: "Much more than a destination",
        destino_p1: "Chimborazo Rey offers a complete tourism experience in one of the most impressive landscapes of Ecuador. In one place you can eat, rest and discover the mountain.",
        destino_p2: "We work with the community of Cruz del Arenal, on the Guaranda - Ambato road.",
        punto1: "Adventure restaurant",
        punto2: "Lodge Hotel",
        punto3: "Adventure tourism",
        punto4: "Andean culture",
        punto5: "Nature",
        punto6: "Gastronomy",
        punto7: "Hospitality",
        punto8: "Community tourism",

        exp_titulo: "Our three areas",
        exp1_titulo: "Adventure Restaurant",
        exp1_texto: "National and international food, vegan options, coffee shop and our own craft beer.",
        exp1_boton: "See restaurant",
        exp2_titulo: "Lodge Hotel",
        exp2_texto: "Family, group and double rooms with heating and views of the volcano.",
        exp2_boton: "See Lodge",
        exp3_titulo: "Travel Explore",
        exp3_texto: "Climbs, horse rides, cycling and night trekking with specialised guides.",
        exp3_boton: "See adventures",

        nosotros_titulo: "About us",
        nosotros_p1: "Chimborazo Rey is located at a strategic point on the Guaranda - Ambato road, at the foot of the Chimborazo volcano.",
        nosotros_p2: "We want to be a tourism landmark for Guaranda and the province of Bolivar, promoting community tourism.",

        mision_titulo: "Mission",
        mision_texto: "To provide a complete and high quality tourism experience joining lodging, food and adventure, with family hospitality and commitment to the community of Cruz del Arenal.",
        mision1: "Warm and safe lodging",
        mision2: "High altitude cuisine",
        mision3: "Guided experiences",
        mision4: "Sustainable development",

        vision_titulo: "Vision 2030",
        vision_texto: "To be a benchmark of community and sustainable tourism in Bolivar and the Andean region of Ecuador, standing out for service quality and positive impact.",
        vision1: "Service excellence",
        vision2: "Local economic impact",
        vision3: "Cultural appreciation",
        vision4: "Environmental care",

        valores_titulo: "Our values",
        valor1_titulo: "Sustainability",
        valor1_texto: "We take care of the paramo around us and promote responsible practices.",
        valor2_titulo: "Community",
        valor2_texto: "We work with the community of Cruz del Arenal to create shared benefits.",
        valor3_titulo: "Hospitality",
        valor3_texto: "We welcome every visitor as part of the family.",
        valor4_titulo: "Excellence",
        valor4_texto: "We always improve our services to give safe experiences.",
        valor5_titulo: "Culture",
        valor5_texto: "We value and share the Andean culture of this territory.",

        ubicacion_titulo: "Where we are",
        ubicacion_texto: "We are in the Cruz del Arenal sector, on the Guaranda - Ambato road, at about 4,250 metres above sea level.",
        ubi_pais: "Country",
        ubi_provincia: "Province",
        ubi_canton: "Canton",
        ubi_sector: "Sector",
        ubi_via: "Road",
        ubi_altitud: "Altitude",
        ubi_altitud_dato: "approx. 4,250 m a.s.l.",
        ubi_nota: "Note: the official Google Maps map of the business must be placed here.",

        contacto_titulo: "Contact us",
        contacto_texto: "Write to us to book a table, ask about lodging or plan your adventure.",
        contacto_info: "Information",
        contacto_tel: "Phone",
        contacto_correo: "Email",
        boton_llamar: "Call",
        boton_whatsapp: "WhatsApp",
        boton_correo: "Send email",
        boton_mapa: "Directions",

        pie_nav: "Navigation",
        pie_contacto: "Contact",
        pie_ubicacion: "Location",
        pie_derechos: "All rights reserved.",
        wa_flotante: "Write to us",

        form_nombre: "Full name",
        form_telefono: "Phone",
        form_correo: "Email address",
        form_comentarios: "Comments",
        form_enviar: "Send request",
        form_aviso: "This form does not save data on any server. When you send it, WhatsApp opens with the summary.",

        resto_titulo: "Flavours in the highlands",
        resto_texto: "A dining experience at 4,250 metres above sea level.",
        resto_boton1: "See the menu",
        resto_boton2: "Book a table",
        resto_sobre: "About the restaurant",
        resto_p1: "We offer national and international dishes, and also vegan and vegetarian options.",
        resto_p2: "We have a coffee shop, Chimborazo Rey craft beer, large rooms and a cosy atmosphere.",
        serv1_titulo: "National and international food",
        serv1_texto: "Ecuadorian and international dishes.",
        serv2_titulo: "Vegan options",
        serv2_texto: "Vegan and vegetarian alternatives.",
        serv3_titulo: "Coffee shop",
        serv3_texto: "Coffee and hot drinks for the cold.",
        serv4_titulo: "Craft beer",
        serv4_texto: "Our own Chimborazo Rey beer.",
        serv5_titulo: "Large rooms",
        serv5_texto: "Space for groups and families.",
        serv6_titulo: "Cosy atmosphere",
        serv6_texto: "A warm place after the mountain.",
        pagos_titulo: "Payment methods",
        pago1: "Card",
        pago2: "Cash",
        pago3: "Bank transfer",

        menu_titulo: "Our menu",
        menu_texto: "Use the buttons to see the dishes by category.",
        filtro_todos: "All",
        cat_pollo: "Chicken",
        cat_cerdo: "Pork",
        cat_carnes: "Meat",
        cat_pescados: "Fish",
        cat_camarones: "Shrimp",
        cat_tradicional: "Traditional",
        cat_desayunos: "Breakfast",
        cat_almuerzos: "Set lunches",
        cat_cafeteria: "Coffee shop",
        plato_pendiente: "Dish to be defined",
        plato_texto: "Space reserved for a dish of this category.",
        precio_pendiente: "Price to be confirmed",
        menu_aviso: "Important: the dishes and prices must be copied from the official Chimborazo Rey menu.",

        galeria_titulo: "Photo gallery",
        galeria_texto: "Click a photo to see it bigger.",

        reserva_titulo: "Book a table",
        form_personas: "Number of people",
        form_fecha: "Date",
        form_hora: "Time",

        lodge_titulo: "Rest among the mountains",
        lodge_texto: "Lodging at about 4,250 metres above sea level, at the foot of Chimborazo.",
        lodge_boton: "Check availability",
        hab_titulo: "Our rooms",
        hab1_titulo: "Family rooms",
        hab1_texto: "Large spaces so the family can rest together.",
        hab2_titulo: "Group rooms",
        hab2_texto: "Ideal for groups of travellers and expeditions.",
        hab3_titulo: "Double rooms",
        hab3_texto: "A comfortable and warm space for couples.",
        hab_precio: "Price on request.",
        hab_boton: "Ask",

        servicios_titulo: "Hotel services",
        sh1: "Heating",
        sh2: "24 hour security",
        sh3: "Security cameras",
        sh4: "Internet",
        sh5: "Cable television",
        sh6: "Kitchen area",
        sh7: "Living room",
        sh8: "Tour packages",
        sh9: "View of the volcano",

        reserva_lodge: "Request lodging",
        form_nacionalidad: "Nationality",
        form_tipo: "Room type",
        form_huespedes: "Number of guests",
        form_entrada: "Check in date",
        form_salida: "Check out date",
        reco_titulo: "Recommendations",
        reco1: "Arrive early and rest before climbing.",
        reco2: "Drink plenty of water during the day.",
        reco3: "Bring warm clothes, the nights are cold.",
        reco4: "Ask us about the tour packages.",

        travel_titulo: "The mountain is waiting",
        travel_texto: "Experiences in the Andean paramo with specialised guides and mountain equipment.",
        travel_boton: "See activities",
        act_titulo: "Our activities",
        act1_titulo: "Chimborazo Volcano Summit",
        act1_texto: "Climb to the summit of the highest volcano in Ecuador.",
        act2_titulo: "Carihuairazo Volcano Summit",
        act2_texto: "Climb to the central summit of Carihuairazo, next to Chimborazo.",
        act3_titulo: "Horse rides",
        act3_texto: "Horse routes to hot springs, viewpoints, the antennas, Carihuairazo and the Frozen Lagoon.",
        act4_titulo: "Downhill cycling",
        act4_texto: "Bike descent from the heights of Chimborazo.",
        act5_titulo: "Night trekking",
        act5_texto: "Night walk to see the constellations and hear the stories of the area.",
        act_dificultad: "Difficulty",
        act_precio: "Price",
        act_ver: "See details",
        act_consultar: "Ask",
        act_sin_precio: "Price on request",
        act_incluye: "What is included",
        act_equipo: "Equipment",
        act_recomendaciones: "Recommendations",
        act_cerrar: "Close",

        niveles_titulo: "Difficulty levels",
        nivel_bajo: "Low",
        nivel_bajo_medio: "Low - Medium",
        nivel_medio: "Medium",
        nivel_medio_alto: "Medium - High",
        nivel_bajo_txt: "For almost all visitors, no experience needed.",
        nivel_bajo_medio_txt: "Needs basic physical condition.",
        nivel_medio_txt: "Needs good physical condition and altitude adaptation.",
        nivel_medio_alto_txt: "Demanding high mountain activity.",
        niveles_nota: "These levels are a reference and are confirmed when booking.",

        seguridad_titulo: "Safety",
        seguridad_texto: "Every trip is planned with guides, mountain equipment and support.",
        seg1: "Specialised guides",
        seg2: "Certified guides when required",
        seg3: "First aid",
        seg4: "Transport in some activities",
        seg5: "Mountain equipment",
        seg6: "Helmets",
        seg7: "Harness",
        seg8: "Ropes",
        seg9: "Ice axe",
        seg10: "Crampons",
        seg11: "Headlamp",
        seg12: "Trekking poles",
        seguridad_aviso: "Important: no mountain activity is free of risk. The trip can change or be cancelled because of the weather or the condition of the group. The guide always decides thinking about safety.",

        consulta_titulo: "Ask about an activity",
        form_actividad: "Activity you are interested in",
        form_participantes: "Number of participants",
        form_elegir: "Choose an option"
    },

    /* ---------- FRANCES ---------- */
    fr: {
        nav_inicio: "Accueil",
        nav_restaurante: "Restaurant",
        nav_lodge: "Lodge Hotel",
        nav_travel: "Travel Explore",
        nav_contacto: "Contact",
        nav_reservar: "Reserver",
        menu_abrir: "Menu",

        portada_sub: "Une experience dans les hauteurs de l'Equateur",
        portada_texto: "Gastronomie, hebergement et aventure au pied du volcan Chimborazo.",
        portada_boton1: "En savoir plus",
        portada_boton2: "Reserver",

        destino_titulo: "Bien plus qu'une destination",
        destino_p1: "Chimborazo Rey offre une experience touristique complete dans un des paysages les plus impressionnants de l'Equateur. Au meme endroit vous pouvez manger, vous reposer et decouvrir la montagne.",
        destino_p2: "Nous travaillons avec la communaute de Cruz del Arenal, sur la route Guaranda - Ambato.",
        punto1: "Restaurant d'aventure",
        punto2: "Lodge Hotel",
        punto3: "Tourisme d'aventure",
        punto4: "Culture andine",
        punto5: "Nature",
        punto6: "Gastronomie",
        punto7: "Hospitalite",
        punto8: "Tourisme communautaire",

        exp_titulo: "Nos trois espaces",
        exp1_titulo: "Restaurant d'Aventure",
        exp1_texto: "Cuisine nationale et internationale, options veganes, coffee shop et biere artisanale maison.",
        exp1_boton: "Voir le restaurant",
        exp2_titulo: "Lodge Hotel",
        exp2_texto: "Chambres familiales, de groupe et doubles avec chauffage et vue sur le volcan.",
        exp2_boton: "Voir le Lodge",
        exp3_titulo: "Travel Explore",
        exp3_texto: "Ascensions, randonnees a cheval, velo et trekking nocturne avec des guides specialises.",
        exp3_boton: "Voir les aventures",

        nosotros_titulo: "A propos de nous",
        nosotros_p1: "Chimborazo Rey se trouve a un point strategique de la route Guaranda - Ambato, au pied du volcan Chimborazo.",
        nosotros_p2: "Nous voulons etre une reference touristique de Guaranda et de la province de Bolivar, en encourageant le tourisme communautaire.",

        mision_titulo: "Mission",
        mision_texto: "Offrir une experience touristique complete et de qualite qui reunit hebergement, gastronomie et aventure, avec une hospitalite familiale et un engagement envers la communaute de Cruz del Arenal.",
        mision1: "Hebergement chaleureux et sur",
        mision2: "Gastronomie d'altitude",
        mision3: "Experiences avec guides",
        mision4: "Developpement durable",

        vision_titulo: "Vision 2030",
        vision_texto: "Etre une reference du tourisme communautaire et durable de Bolivar et de la region andine de l'Equateur, en se distinguant par la qualite du service et un impact positif.",
        vision1: "Excellence du service",
        vision2: "Impact economique local",
        vision3: "Valorisation culturelle",
        vision4: "Protection de l'environnement",

        valores_titulo: "Nos valeurs",
        valor1_titulo: "Durabilite",
        valor1_texto: "Nous prenons soin du paramo qui nous entoure et encourageons des pratiques responsables.",
        valor2_titulo: "Communaute",
        valor2_texto: "Nous travaillons avec la communaute de Cruz del Arenal pour creer des benefices partages.",
        valor3_titulo: "Hospitalite",
        valor3_texto: "Nous accueillons chaque visiteur comme un membre de la famille.",
        valor4_titulo: "Excellence",
        valor4_texto: "Nous ameliorons toujours nos services pour offrir des experiences sures.",
        valor5_titulo: "Culture",
        valor5_texto: "Nous valorisons et partageons la culture andine de ce territoire.",

        ubicacion_titulo: "Ou nous sommes",
        ubicacion_texto: "Nous sommes dans le secteur Cruz del Arenal, sur la route Guaranda - Ambato, a environ 4 250 metres d'altitude.",
        ubi_pais: "Pays",
        ubi_provincia: "Province",
        ubi_canton: "Canton",
        ubi_sector: "Secteur",
        ubi_via: "Route",
        ubi_altitud: "Altitude",
        ubi_altitud_dato: "env. 4 250 m d'altitude",
        ubi_nota: "Note : la carte officielle Google Maps de l'etablissement doit etre placee ici.",

        contacto_titulo: "Contactez-nous",
        contacto_texto: "Ecrivez-nous pour reserver une table, demander un hebergement ou preparer votre aventure.",
        contacto_info: "Informations",
        contacto_tel: "Telephone",
        contacto_correo: "Courriel",
        boton_llamar: "Appeler",
        boton_whatsapp: "WhatsApp",
        boton_correo: "Envoyer un courriel",
        boton_mapa: "Itineraire",

        pie_nav: "Navigation",
        pie_contacto: "Contact",
        pie_ubicacion: "Emplacement",
        pie_derechos: "Tous droits reserves.",
        wa_flotante: "Ecrivez-nous",

        form_nombre: "Nom complet",
        form_telefono: "Telephone",
        form_correo: "Adresse electronique",
        form_comentarios: "Commentaires",
        form_enviar: "Envoyer la demande",
        form_aviso: "Ce formulaire n'enregistre aucune donnee sur un serveur. En l'envoyant, WhatsApp s'ouvre avec le resume.",

        resto_titulo: "Saveurs des hauteurs",
        resto_texto: "Une experience gastronomique a 4 250 metres d'altitude.",
        resto_boton1: "Voir le menu",
        resto_boton2: "Reserver une table",
        resto_sobre: "A propos du restaurant",
        resto_p1: "Nous proposons des plats nationaux et internationaux, ainsi que des options veganes et vegetariennes.",
        resto_p2: "Nous avons un coffee shop, la biere artisanale Chimborazo Rey, de grandes salles et une ambiance chaleureuse.",
        serv1_titulo: "Cuisine nationale et internationale",
        serv1_texto: "Plats equatoriens et internationaux.",
        serv2_titulo: "Options veganes",
        serv2_texto: "Alternatives veganes et vegetariennes.",
        serv3_titulo: "Coffee shop",
        serv3_texto: "Cafe et boissons chaudes pour le froid.",
        serv4_titulo: "Biere artisanale",
        serv4_texto: "Notre propre biere Chimborazo Rey.",
        serv5_titulo: "Grandes salles",
        serv5_texto: "De la place pour les groupes et les familles.",
        serv6_titulo: "Ambiance chaleureuse",
        serv6_texto: "Un lieu chaleureux apres la montagne.",
        pagos_titulo: "Moyens de paiement",
        pago1: "Carte",
        pago2: "Especes",
        pago3: "Virement",

        menu_titulo: "Notre menu",
        menu_texto: "Utilisez les boutons pour voir les plats par categorie.",
        filtro_todos: "Tous",
        cat_pollo: "Poulet",
        cat_cerdo: "Porc",
        cat_carnes: "Viandes",
        cat_pescados: "Poissons",
        cat_camarones: "Crevettes",
        cat_tradicional: "Traditionnels",
        cat_desayunos: "Petits-dejeuners",
        cat_almuerzos: "Menus du jour",
        cat_cafeteria: "Coffee shop",
        plato_pendiente: "Plat a definir",
        plato_texto: "Espace reserve a un plat de cette categorie.",
        precio_pendiente: "Prix a confirmer",
        menu_aviso: "Important : les plats et les prix doivent etre copies du menu officiel de Chimborazo Rey.",

        galeria_titulo: "Galerie de photos",
        galeria_texto: "Cliquez sur une photo pour la voir en grand.",

        reserva_titulo: "Reserver une table",
        form_personas: "Nombre de personnes",
        form_fecha: "Date",
        form_hora: "Heure",

        lodge_titulo: "Reposez-vous au coeur des montagnes",
        lodge_texto: "Hebergement a environ 4 250 metres d'altitude, au pied du Chimborazo.",
        lodge_boton: "Verifier les disponibilites",
        hab_titulo: "Nos chambres",
        hab1_titulo: "Chambres familiales",
        hab1_texto: "De grands espaces pour que la famille se repose ensemble.",
        hab2_titulo: "Chambres de groupe",
        hab2_texto: "Ideales pour les groupes de voyageurs et les expeditions.",
        hab3_titulo: "Chambres doubles",
        hab3_texto: "Un espace confortable et chaleureux pour les couples.",
        hab_precio: "Prix sur demande.",
        hab_boton: "Demander",

        servicios_titulo: "Services de l'hotel",
        sh1: "Chauffage",
        sh2: "Securite 24 heures",
        sh3: "Cameras de securite",
        sh4: "Internet",
        sh5: "Television par cable",
        sh6: "Espace cuisine",
        sh7: "Salon",
        sh8: "Forfaits touristiques",
        sh9: "Vue sur le volcan",

        reserva_lodge: "Demander un hebergement",
        form_nacionalidad: "Nationalite",
        form_tipo: "Type de chambre",
        form_huespedes: "Nombre de personnes",
        form_entrada: "Date d'arrivee",
        form_salida: "Date de depart",
        reco_titulo: "Recommandations",
        reco1: "Arrivez tot et reposez-vous avant de monter.",
        reco2: "Buvez beaucoup d'eau pendant la journee.",
        reco3: "Apportez des vetements chauds, les nuits sont froides.",
        reco4: "Demandez-nous les forfaits touristiques.",

        travel_titulo: "La montagne vous attend",
        travel_texto: "Des experiences dans le paramo andin avec des guides specialises et du materiel de montagne.",
        travel_boton: "Voir les activites",
        act_titulo: "Nos activites",
        act1_titulo: "Sommet du volcan Chimborazo",
        act1_texto: "Ascension du sommet du plus haut volcan de l'Equateur.",
        act2_titulo: "Sommet du volcan Carihuairazo",
        act2_texto: "Ascension du sommet central du Carihuairazo, voisin du Chimborazo.",
        act3_titulo: "Randonnees a cheval",
        act3_texto: "Itineraires a cheval vers les sources chaudes, les belvederes, les antennes, le Carihuairazo et la Lagune Gelee.",
        act4_titulo: "Descente a velo",
        act4_texto: "Descente a velo depuis les hauteurs du Chimborazo.",
        act5_titulo: "Trekking nocturne",
        act5_texto: "Marche de nuit pour voir les constellations et ecouter les histoires de la region.",
        act_dificultad: "Difficulte",
        act_precio: "Prix",
        act_ver: "Voir le detail",
        act_consultar: "Demander",
        act_sin_precio: "Prix sur demande",
        act_incluye: "Ce qui est inclus",
        act_equipo: "Equipement",
        act_recomendaciones: "Recommandations",
        act_cerrar: "Fermer",

        niveles_titulo: "Niveaux de difficulte",
        nivel_bajo: "Faible",
        nivel_bajo_medio: "Faible - Moyen",
        nivel_medio: "Moyen",
        nivel_medio_alto: "Moyen - Eleve",
        nivel_bajo_txt: "Pour presque tous les visiteurs, sans experience.",
        nivel_bajo_medio_txt: "Demande une condition physique de base.",
        nivel_medio_txt: "Demande une bonne condition physique et l'adaptation a l'altitude.",
        nivel_medio_alto_txt: "Activite exigeante de haute montagne.",
        niveles_nota: "Ces niveaux sont indicatifs et sont confirmes au moment de la reservation.",

        seguridad_titulo: "Securite",
        seguridad_texto: "Chaque sortie est planifiee avec des guides, du materiel de montagne et un accompagnement.",
        seg1: "Guides specialises",
        seg2: "Guides certifies si necessaire",
        seg3: "Premiers secours",
        seg4: "Transport dans certaines activites",
        seg5: "Materiel de montagne",
        seg6: "Casques",
        seg7: "Baudrier",
        seg8: "Cordes",
        seg9: "Piolet",
        seg10: "Crampons",
        seg11: "Lampe frontale",
        seg12: "Batons de randonnee",
        seguridad_aviso: "Important : aucune activite de montagne n'est sans risque. La sortie peut changer ou etre annulee a cause du temps ou de l'etat du groupe. Le guide decide toujours en pensant a la securite.",

        consulta_titulo: "Demander une activite",
        form_actividad: "Activite qui vous interesse",
        form_participantes: "Nombre de participants",
        form_elegir: "Choisissez une option"
    },

    /* ---------- ALEMAN ---------- */
    de: {
        nav_inicio: "Startseite",
        nav_restaurante: "Restaurant",
        nav_lodge: "Lodge Hotel",
        nav_travel: "Travel Explore",
        nav_contacto: "Kontakt",
        nav_reservar: "Reservieren",
        menu_abrir: "Menu",

        portada_sub: "Ein Erlebnis in den Hoehen Ecuadors",
        portada_texto: "Gastronomie, Unterkunft und Abenteuer am Fusse des Vulkans Chimborazo.",
        portada_boton1: "Mehr erfahren",
        portada_boton2: "Reservieren",

        destino_titulo: "Viel mehr als ein Reiseziel",
        destino_p1: "Chimborazo Rey bietet ein komplettes touristisches Erlebnis in einer der eindrucksvollsten Landschaften Ecuadors. An einem Ort koennen Sie essen, sich ausruhen und den Berg entdecken.",
        destino_p2: "Wir arbeiten mit der Gemeinde Cruz del Arenal an der Strasse Guaranda - Ambato zusammen.",
        punto1: "Abenteuerrestaurant",
        punto2: "Lodge Hotel",
        punto3: "Abenteuertourismus",
        punto4: "Andine Kultur",
        punto5: "Natur",
        punto6: "Gastronomie",
        punto7: "Gastfreundschaft",
        punto8: "Gemeindetourismus",

        exp_titulo: "Unsere drei Bereiche",
        exp1_titulo: "Abenteuerrestaurant",
        exp1_texto: "Nationale und internationale Kueche, vegane Optionen, Coffee Shop und eigenes Craft-Bier.",
        exp1_boton: "Restaurant ansehen",
        exp2_titulo: "Lodge Hotel",
        exp2_texto: "Familien-, Gruppen- und Doppelzimmer mit Heizung und Blick auf den Vulkan.",
        exp2_boton: "Lodge ansehen",
        exp3_titulo: "Travel Explore",
        exp3_texto: "Besteigungen, Ausritte, Radtouren und Nachttrekking mit spezialisierten Guides.",
        exp3_boton: "Abenteuer ansehen",

        nosotros_titulo: "Ueber uns",
        nosotros_p1: "Chimborazo Rey liegt an einem strategischen Punkt der Strasse Guaranda - Ambato, am Fusse des Vulkans Chimborazo.",
        nosotros_p2: "Wir wollen ein touristischer Bezugspunkt fuer Guaranda und die Provinz Bolivar sein und den Gemeindetourismus foerdern.",

        mision_titulo: "Mission",
        mision_texto: "Ein vollstaendiges und hochwertiges touristisches Erlebnis bieten, das Unterkunft, Gastronomie und Abenteuer verbindet, mit familiaerer Gastfreundschaft und Engagement fuer die Gemeinde Cruz del Arenal.",
        mision1: "Herzliche und sichere Unterkunft",
        mision2: "Kueche in der Hoehe",
        mision3: "Begleitete Erlebnisse",
        mision4: "Nachhaltige Entwicklung",

        vision_titulo: "Vision 2030",
        vision_texto: "Ein Vorbild fuer Gemeinde- und nachhaltigen Tourismus in Bolivar und der Andenregion Ecuadors sein, mit hervorragendem Service und positiver Wirkung.",
        vision1: "Hervorragender Service",
        vision2: "Lokale wirtschaftliche Wirkung",
        vision3: "Kulturelle Wertschaetzung",
        vision4: "Umweltschutz",

        valores_titulo: "Unsere Werte",
        valor1_titulo: "Nachhaltigkeit",
        valor1_texto: "Wir schuetzen den Paramo um uns herum und foerdern verantwortungsvolle Praktiken.",
        valor2_titulo: "Gemeinschaft",
        valor2_texto: "Wir arbeiten mit der Gemeinde Cruz del Arenal fuer gemeinsamen Nutzen.",
        valor3_titulo: "Gastfreundschaft",
        valor3_texto: "Wir empfangen jeden Gast als Teil der Familie.",
        valor4_titulo: "Exzellenz",
        valor4_texto: "Wir verbessern unsere Leistungen immer, um sichere Erlebnisse zu bieten.",
        valor5_titulo: "Kultur",
        valor5_texto: "Wir schaetzen und teilen die andine Kultur dieses Gebiets.",

        ubicacion_titulo: "Wo wir sind",
        ubicacion_texto: "Wir befinden uns im Sektor Cruz del Arenal an der Strasse Guaranda - Ambato, auf etwa 4.250 Metern ueber dem Meeresspiegel.",
        ubi_pais: "Land",
        ubi_provincia: "Provinz",
        ubi_canton: "Kanton",
        ubi_sector: "Sektor",
        ubi_via: "Strasse",
        ubi_altitud: "Hoehe",
        ubi_altitud_dato: "ca. 4.250 m ue. M.",
        ubi_nota: "Hinweis: Hier muss die offizielle Google-Maps-Karte des Betriebs eingefuegt werden.",

        contacto_titulo: "Kontaktieren Sie uns",
        contacto_texto: "Schreiben Sie uns, um einen Tisch zu reservieren, nach einer Unterkunft zu fragen oder Ihr Abenteuer zu planen.",
        contacto_info: "Information",
        contacto_tel: "Telefon",
        contacto_correo: "E-Mail",
        boton_llamar: "Anrufen",
        boton_whatsapp: "WhatsApp",
        boton_correo: "E-Mail senden",
        boton_mapa: "Anfahrt",

        pie_nav: "Navigation",
        pie_contacto: "Kontakt",
        pie_ubicacion: "Standort",
        pie_derechos: "Alle Rechte vorbehalten.",
        wa_flotante: "Schreiben Sie uns",

        form_nombre: "Vollstaendiger Name",
        form_telefono: "Telefon",
        form_correo: "E-Mail-Adresse",
        form_comentarios: "Anmerkungen",
        form_enviar: "Anfrage senden",
        form_aviso: "Dieses Formular speichert keine Daten auf einem Server. Beim Senden oeffnet sich WhatsApp mit der Zusammenfassung.",

        resto_titulo: "Aromen in der Hoehe",
        resto_texto: "Ein kulinarisches Erlebnis auf 4.250 Metern ueber dem Meeresspiegel.",
        resto_boton1: "Speisekarte ansehen",
        resto_boton2: "Tisch reservieren",
        resto_sobre: "Ueber das Restaurant",
        resto_p1: "Wir bieten nationale und internationale Gerichte sowie vegane und vegetarische Optionen.",
        resto_p2: "Wir haben einen Coffee Shop, das Craft-Bier Chimborazo Rey, grosse Saele und eine gemuetliche Atmosphaere.",
        serv1_titulo: "Nationale und internationale Kueche",
        serv1_texto: "Ecuadorianische und internationale Gerichte.",
        serv2_titulo: "Vegane Optionen",
        serv2_texto: "Vegane und vegetarische Alternativen.",
        serv3_titulo: "Coffee Shop",
        serv3_texto: "Kaffee und heisse Getraenke fuer die Kaelte.",
        serv4_titulo: "Craft-Bier",
        serv4_texto: "Unser eigenes Bier Chimborazo Rey.",
        serv5_titulo: "Grosse Saele",
        serv5_texto: "Platz fuer Gruppen und Familien.",
        serv6_titulo: "Gemuetliche Atmosphaere",
        serv6_texto: "Ein warmer Ort nach dem Berg.",
        pagos_titulo: "Zahlungsmittel",
        pago1: "Karte",
        pago2: "Bargeld",
        pago3: "Ueberweisung",

        menu_titulo: "Unsere Speisekarte",
        menu_texto: "Nutzen Sie die Schaltflaechen, um die Gerichte nach Kategorie zu sehen.",
        filtro_todos: "Alle",
        cat_pollo: "Haehnchen",
        cat_cerdo: "Schwein",
        cat_carnes: "Fleisch",
        cat_pescados: "Fisch",
        cat_camarones: "Garnelen",
        cat_tradicional: "Traditionell",
        cat_desayunos: "Fruehstueck",
        cat_almuerzos: "Mittagsmenues",
        cat_cafeteria: "Coffee Shop",
        plato_pendiente: "Gericht noch festzulegen",
        plato_texto: "Platz fuer ein Gericht dieser Kategorie.",
        precio_pendiente: "Preis wird bestaetigt",
        menu_aviso: "Wichtig: Die Gerichte und Preise muessen aus der offiziellen Speisekarte von Chimborazo Rey uebernommen werden.",

        galeria_titulo: "Fotogalerie",
        galeria_texto: "Klicken Sie auf ein Foto, um es groesser zu sehen.",

        reserva_titulo: "Tisch reservieren",
        form_personas: "Anzahl der Personen",
        form_fecha: "Datum",
        form_hora: "Uhrzeit",

        lodge_titulo: "Erholen Sie sich zwischen den Bergen",
        lodge_texto: "Unterkunft auf etwa 4.250 Metern ueber dem Meeresspiegel, am Fusse des Chimborazo.",
        lodge_boton: "Verfuegbarkeit anfragen",
        hab_titulo: "Unsere Zimmer",
        hab1_titulo: "Familienzimmer",
        hab1_texto: "Grosse Raeume, damit die Familie zusammen ausruhen kann.",
        hab2_titulo: "Gruppenzimmer",
        hab2_texto: "Ideal fuer Reisegruppen und Expeditionen.",
        hab3_titulo: "Doppelzimmer",
        hab3_texto: "Ein bequemer und warmer Raum fuer Paare.",
        hab_precio: "Preis auf Anfrage.",
        hab_boton: "Anfragen",

        servicios_titulo: "Leistungen des Hotels",
        sh1: "Heizung",
        sh2: "Sicherheit 24 Stunden",
        sh3: "Ueberwachungskameras",
        sh4: "Internet",
        sh5: "Kabelfernsehen",
        sh6: "Kuechenbereich",
        sh7: "Aufenthaltsraum",
        sh8: "Tourpakete",
        sh9: "Blick auf den Vulkan",

        reserva_lodge: "Unterkunft anfragen",
        form_nacionalidad: "Nationalitaet",
        form_tipo: "Zimmertyp",
        form_huespedes: "Anzahl der Gaeste",
        form_entrada: "Anreisedatum",
        form_salida: "Abreisedatum",
        reco_titulo: "Empfehlungen",
        reco1: "Kommen Sie frueh an und ruhen Sie sich vor dem Aufstieg aus.",
        reco2: "Trinken Sie tagsueber viel Wasser.",
        reco3: "Bringen Sie warme Kleidung mit, die Naechte sind kalt.",
        reco4: "Fragen Sie uns nach den Tourpaketen.",

        travel_titulo: "Der Berg wartet auf Sie",
        travel_texto: "Erlebnisse im andinen Paramo mit spezialisierten Guides und Bergausruestung.",
        travel_boton: "Aktivitaeten ansehen",
        act_titulo: "Unsere Aktivitaeten",
        act1_titulo: "Gipfel des Vulkans Chimborazo",
        act1_texto: "Aufstieg zum Gipfel des hoechsten Vulkans Ecuadors.",
        act2_titulo: "Gipfel des Vulkans Carihuairazo",
        act2_texto: "Aufstieg zum Zentralgipfel des Carihuairazo neben dem Chimborazo.",
        act3_titulo: "Ausritte",
        act3_texto: "Reitrouten zu heissen Quellen, Aussichtspunkten, den Antennen, zum Carihuairazo und zur Gefrorenen Lagune.",
        act4_titulo: "Radabfahrt",
        act4_texto: "Abfahrt mit dem Rad aus den Hoehen des Chimborazo.",
        act5_titulo: "Nachttrekking",
        act5_texto: "Nachtwanderung, um die Sternbilder zu sehen und die Geschichten der Gegend zu hoeren.",
        act_dificultad: "Schwierigkeit",
        act_precio: "Preis",
        act_ver: "Details ansehen",
        act_consultar: "Anfragen",
        act_sin_precio: "Preis auf Anfrage",
        act_incluye: "Im Preis enthalten",
        act_equipo: "Ausruestung",
        act_recomendaciones: "Empfehlungen",
        act_cerrar: "Schliessen",

        niveles_titulo: "Schwierigkeitsgrade",
        nivel_bajo: "Niedrig",
        nivel_bajo_medio: "Niedrig - Mittel",
        nivel_medio: "Mittel",
        nivel_medio_alto: "Mittel - Hoch",
        nivel_bajo_txt: "Fuer fast alle Gaeste, ohne Vorerfahrung.",
        nivel_bajo_medio_txt: "Erfordert eine Grundkondition.",
        nivel_medio_txt: "Erfordert gute Kondition und Anpassung an die Hoehe.",
        nivel_medio_alto_txt: "Anspruchsvolle Hochgebirgsaktivitaet.",
        niveles_nota: "Diese Stufen sind Richtwerte und werden bei der Buchung bestaetigt.",

        seguridad_titulo: "Sicherheit",
        seguridad_texto: "Jede Tour wird mit Guides, Bergausruestung und Begleitung geplant.",
        seg1: "Spezialisierte Guides",
        seg2: "Zertifizierte Guides wenn noetig",
        seg3: "Erste Hilfe",
        seg4: "Transport bei einigen Aktivitaeten",
        seg5: "Bergausruestung",
        seg6: "Helme",
        seg7: "Klettergurt",
        seg8: "Seile",
        seg9: "Eispickel",
        seg10: "Steigeisen",
        seg11: "Stirnlampe",
        seg12: "Trekkingstoecke",
        seguridad_aviso: "Wichtig: Keine Bergaktivitaet ist frei von Risiken. Die Tour kann sich wegen des Wetters oder des Zustands der Gruppe aendern oder abgesagt werden. Der Guide entscheidet immer mit Blick auf die Sicherheit.",

        consulta_titulo: "Nach einer Aktivitaet fragen",
        form_actividad: "Aktivitaet die Sie interessiert",
        form_participantes: "Anzahl der Teilnehmer",
        form_elegir: "Waehlen Sie eine Option"
    }
};
